### PR TITLE
Update Illuminate components to v8

### PR DESCRIPTION
**Pull request by bakerkretzmar**
Does what it says on the box 😄 

@damiani I'm not positive that this won't break anything in any existing sites... thoughts? Might not be a huge deal to leave it until v2.

### CODE REVIEW

**Comment by damiani** [comment]
@bakerkretzmar Yeah this worries me a bit, too—I _think_ it should be fine (tests pass, and the collection change preserves pre-v8 behavior), but I'm not sure this upgrade buys us anything of value, so it may not be worth the risk.

**Comment by bakerkretzmar** [comment]
Sounds good, we can shelve it for now. Nice to know at least that it'll be pretty simple 😅

**Comment by keithbrink** [comment]
Just did some work on a PR before I noticed this one 😅

I know this is a little niche, but I would love support for the 8.0 components so I can use the Notion API package in Jigsaw:

https://github.com/5am-code/laravel-notion-api

**Comment by bakerkretzmar** [comment]
We should probably take another look at this, I think we'll have to make this upgrade to be able to support PHP 8.1. See #601.

**Review by damiani — APPROVED** [review]

**Pull request merged**
